title: "KPIT APEX Lab: Linux Assignment Page"
markdown: kramdown
theme: null             # ensure no default theme UI
plugins: []             # keep it lean
permalink: pretty       # clean URLs like /signal/
kramdown:
  input: GFM            # GitHub-flavored Markdown
